FROM openjdk:11
COPY target/Currency-Exchange-Service-0.0.1-SNAPSHOT.jar Currency-Exchange-Service-0.0.1-SNAPSHOT.jar
EXPOSE 8085
ENTRYPOINT ["java","-jar", "Currency-Exchange-Service-0.0.1-SNAPSHOT.jar"]